# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Frigate
version: "0.1"
slug: frigate
description: Frigate NVR with VAAPI and Coral support
url: "https://github.com/jo4santos/hass-repo/tree/main/frigate"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
